"""Bake the biome lookup raster -> satisfactory_opt/biome_raster.py.

The biome regions are hand-painted as flat colours in
``satisfactory_opt/assets/hue_map.png`` (one colour per biome), and
``satisfactory_opt/assets/color_map.txt`` maps each ``rrggbb`` hex to a biome
name. This baker:

* snaps every map pixel to its nearest canonical biome colour (so anti-aliased
  edges and altitude-shaded pixels resolve cleanly), with pure black as a
  "void" anchor for the off-map background/ocean,
* fills every void cell with the biome of its nearest *land* cell, so a point
  in the sea resolves along the coastline to the nearest biome,
* serialises the indexed grid (zlib+base64) so the runtime needs no
  PIL/numpy/scipy.

Re-run after editing hue_map.png or color_map.txt:

    pip install pillow numpy scipy
    python bake_biomes.py
"""
import base64
import os
import zlib

import numpy as np
from PIL import Image
from scipy import ndimage

ASSETS = os.path.join(os.path.dirname(__file__), "satisfactory_opt", "assets")
HUE_MAP = os.path.join(ASSETS, "hue_map.png")
COLOR_MAP = os.path.join(ASSETS, "color_map.txt")
OUT = os.path.join(os.path.dirname(__file__), "satisfactory_opt", "biome_raster.py")

N = 1024            # baked grid resolution (cells); ~730 game-units/cell


def load_color_map() -> list[tuple[str, tuple[int, int, int]]]:
    """[(name, (r,g,b)), ...] in file order -> defines the baked index."""
    out = []
    with open(COLOR_MAP) as f:
        for line in f:
            line = line.strip()
            if "=" not in line:
                continue
            hexc, name = line.split("=", 1)
            hexc = hexc.strip().lower()
            rgb = tuple(int(hexc[i:i + 2], 16) for i in (0, 2, 4))
            out.append((name.strip(), rgb))
    return out


def main():
    biomes = load_color_map()
    names = [b[0] for b in biomes]
    # canonical palette: the N biome colours + pure black as the "void" anchor.
    palette = np.array([b[1] for b in biomes] + [(0, 0, 0)], np.float32)
    VOID = len(biomes)

    im = Image.open(HUE_MAP).convert("RGB").resize((N, N), Image.NEAREST)
    rgb = np.asarray(im).astype(np.float32)

    # snap each pixel to the nearest palette colour (euclidean in RGB)
    d2 = ((rgb[:, :, None, :] - palette[None, None, :, :]) ** 2).sum(-1)
    ids = d2.argmin(-1).astype(np.int16)

    # fill void cells with their nearest land biome
    land = ids != VOID
    if land.any():
        idx = ndimage.distance_transform_edt(~land, return_distances=False,
                                             return_indices=True)
        ids = np.where(land, ids, ids[idx[0], idx[1]])
    ids = ids.astype(np.uint8)

    blob = base64.b64encode(zlib.compress(ids.tobytes(), 9)).decode()
    with open(OUT, "w") as f:
        f.write('"""Baked biome id-raster (generated by bake_biomes.py — do not edit).\n\n')
        f.write("Indexed %dx%d grid, row-major: fx=col/W (west->east), fy=row/H\n" % (N, N))
        f.write("(north->south). Each cell indexes NAMES. zlib+base64; stdlib decode."\
                '"""\n\n')
        f.write("import base64, zlib\n\n")
        f.write("W = %d\nH = %d\n\nNAMES = [\n" % (N, N))
        for nm in names:
            f.write("    %r,\n" % nm)
        f.write("]\n\n_B64 = (\n")
        for i in range(0, len(blob), 100):
            f.write("    %r\n" % blob[i:i + 100])
        f.write(")\n\n\ndef grid() -> bytes:\n")
        f.write('    """Decoded W*H bytes of biome indices (row-major)."""\n')
        f.write("    return zlib.decompress(base64.b64decode(_B64))\n")
    print("wrote %s  (%d biomes, grid %dx%d, %d KB compressed)"
          % (OUT, len(names), N, N, len(blob) // 1024))


if __name__ == "__main__":
    main()
